CREATE TABLE IF NOT EXISTS wallets (
    user_id BIGINT PRIMARY KEY,
    balance BIGINT,
    held_balance BIGINT,
    version BIGINT,
    created_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bank_accounts (
    user_id BIGINT PRIMARY KEY,
    bank_name VARCHAR(255) NOT NULL,
    account_number VARCHAR(255) NOT NULL,
    balance BIGINT,
    created_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    type VARCHAR(255),
    amount BIGINT,
    description VARCHAR(255),
    balance_after BIGINT,
    held_balance_after BIGINT,
    idempotency_key VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP
);

TRUNCATE TABLE transactions RESTART IDENTITY;
TRUNCATE TABLE bank_accounts;
TRUNCATE TABLE wallets;

INSERT INTO wallets (user_id, balance, held_balance, version, created_at)
SELECT user_id, 100000000, 0, 0, NOW()
FROM generate_series(1, 10000) AS user_id;

INSERT INTO bank_accounts (user_id, bank_name, account_number, balance, created_at)
SELECT user_id, 'BCA', '801234' || user_id::text, 100000000, NOW()
FROM generate_series(1, 10000) AS user_id;

INSERT INTO transactions (
    user_id,
    type,
    amount,
    description,
    balance_after,
    held_balance_after,
    idempotency_key,
    created_at
)
SELECT
    user_id,
    'TOPUP',
    100000000,
    'Profiling seed balance',
    100000000,
    0,
    'profiling-seed-' || user_id::text,
    NOW()
FROM generate_series(1, 10000) AS user_id;

CREATE INDEX IF NOT EXISTS idx_transactions_user_id_created_at
    ON transactions (user_id, created_at DESC);
