spring:
  application:
    name: wallet
  datasource:
    url: ${SUPABASE_DB_URL}
    username: ${SUPABASE_DB_USERNAME}
    password: ${SUPABASE_DB_PASSWORD}
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false

  rabbitmq:
    host: shark.rmq.cloudamqp.com
    port: 5672
    username: ovjyezsx
    password: 9LJJ7ZDQTDmRydmSXAnb48FSqImyVfP_
    virtual-host: ovjyezsx

staging:
  links:
    frontend-url: ${FRONTEND_STAGING_URL:not-set}
    backend-url: ${BACKEND_STAGING_URL:not-set}
    database-url: ${DATABASE_STAGING_URL:not-set}